const FLOWS = {
    REGISTER: "YOUR_REGISTER_FLOW_URL",
    GET_COMPONENT: "YOUR_GET_COMPONENT_FLOW_URL",
    UPDATE_COMPONENT: "YOUR_UPDATE_COMPONENT_FLOW_URL",
    DASHBOARD: "YOUR_DASHBOARD_FLOW_URL",
    GET_MOVEMENT_HISTORY_API: "YOUR_MOVEMENT_HISTORY_FLOW_URL"
};

const CONFIG = {
    DEBUG: false,
    APP_URL: ""
};
